# Global variables
title: Felipe Gustavo | Desenvolvedor Front-end
email: felipegdas07@gmail.com
name: Felipe Gustavo
job_title: Desenvolvedor Front-end

social:
  name: Felipe Gustavo
  links:
    - https://twitter.com/felipegsdev
    - https://github.com/felipegs07
    - https://www.linkedin.com/in/felipegdasilva/

lang: pt_BR
google-site-verification: google460580164f1f5077.html
author: 
  twitter: felipegsdev
  card: summary
  picture: /assets/img/photo.jpg
description: >-
  Um blog focado no compartilhamento de conteúdo de desenvolvimento web e front-end. Posts sobre CSS, React, TDD, Jekyll e muito mais...

desc: >-
  Eu sou um desenvolvedor front-end júnior com foco em me desenvolver na criação de web apps e UI. 
  Como programador estou em busca constante de melhores práticas e conhecimento. 
  Gosto de aprender coisas novas, me interesso por javascript e seus frameworks, design de interface/UX e
  Test-Driven Development. 
skills:
  - HTML 5;
  - CSS 3 (sass/scss); Responsive Design; 
  - Javascript (ES6+, JQuery); 
  #- React.js (redux, react-router, hooks); 
  - Automatizadores (Gulp, Webpack, npm);
  - Git, GitHub;
  - Test-Driven Development (Mocha, Chai).
skills_title: Habilidades
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://felipegs07.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
linkedin: https://www.linkedin.com/in/felipegdasilva/
github:  https://github.com/felipegs07
home_titles: '["desenvolvedor front-end.","desenvolvedor web.", "programador júnior.", "apaixonado por CSS."]'
#"desenvolvedor React."
# Build settings
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/js-logo.png

permalink: /:title/
highlighter: rouge
markdown: kramdown
sass:
    style: compressed

minify_html: true

plugins:
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
